#!/usr/bin/env ruby
require 'sqlite3'
require './model.rb'

DATABASE="cards.db"

raw = [[ "name",   "attribute", "rarity", "cost", "attack", "defense" ],
       [ "Amy",    "L", 1, 4, 480, 480 ],
       [ "Betty",  "L", 1, 7, 832, 660 ],
       [ "Cerise", "T", 2, 6, 512, 634 ],
       [ "Danni",  "T", 1, 3, 320, 342 ],
       [ "Elise",  "M", 2, 8, 916, 844 ],
       [ "Fay",    "L", 1, 5, 472, 536 ],
       [ "Ginny",  "M", 4, 15, 1020, 1296 ],
       [ "Helen",  "T", 1, 2, 272, 204 ],
       [ "Izzy",   "C", 1, 3, 320, 342 ],
       [ "Jane",   "L", 2, 8, 844, 916 ],
       [ "Kelly",  "T", 2, 5, 204, 272 ]]

def aa2ahash(aa)
  fields = aa[0]
  aa[1..-1].map { |vals| fields.zip(vals).to_h }
end

puts aa2ahash raw

SQLite3::Database.new( DATABASE ) do |db|
  aa2ahash(raw).each do |params|
    card = Cardstate.new(params)
    card.save || raise("failed to save #{params["name"]}: #{card.missing_fields}")
  end
end
